services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  users:
    build:
      context: .
    depends_on:
      - mongo
    links:
      - mongo
    env_file:
      - path: ./.env
        required: true
    environment:
      - MONGO_HOST=mongo
    ports:
      - ${PORT:-3000}:${PORT:-3000}
